# Available voices: alloy, echo, fable, onyx, nova, shimmer
# Command structure:
#   - name: NameOfCommand
#     modifier: alt
#     key: n
#     hold: 0.8

wingmen:
  board-computer:
    openai:
      api_key: YOUR_API_KEY
    system_prompt: You are the board-computer of the USS Enterprise. You are in the year 2265.
    record_key: end
    tts_voice: nova
    features:
      play_beep_on_sending: false
      play_beep_on_receiving: false
      enable_radio_sound_effect: false
    commands:
      - name: DeployLandingGear
        key: n
      - name: JumpWithQuantumDrive
        key: b
        hold: 0.8
      - name: OpenDoors
        modifier: alt
        key: ;
  atc:
    openai:
      api_key: YOUR_API_KEY
    system_prompt: You are an ATC of a space station.
    record_key: delete
    tts_voice: onyx
    features:
      play_beep_on_sending: true
      play_beep_on_receiving: true
      enable_radio_sound_effect: true
    commands:
      - name: RequestLandingPermission
        modifier: alt
        key: n
      - name: RequestDeparture
        modifier: alt
        key: n

  groot:
    record_key: up
    class:
      module: wingmen.groot # where your custom wingman is located. Use '.' as path separator
      name: Groot # the name of your class within the file/module

  openai-groot:
    openai:
      api_key: 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
    record_key: down
    class:
      module: wingmen.open_ai_groot
      name: OpenAIGroot
      args: # passed to the class constructor as **kwargs dict - optional
        one_liner: I. Am. Groot.
